# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
	config,
	lib,
	pkgs,
	modulesPath,
	...
}: {
	imports = [
		(modulesPath + "/installer/scan/not-detected.nix")
	];

	boot.initrd.availableKernelModules = [
		"nvme"
		"xhci_pci"
		"thunderbolt"
		"usb_storage"
		"sd_mod"
	];
	boot.initrd.kernelModules = [];
	boot.kernelModules = [
		"kvm-amd"
	];
	boot.extraModulePackages = [];

	fileSystems."/" = {
		device = "/dev/disk/by-uuid/8ef13832-00f0-4420-8cbb-24471af14092";
		fsType = "ext4";
	};

	fileSystems."/boot" = {
		device = "/dev/disk/by-uuid/2433-B5CB";
		fsType = "vfat";
		options = [ "fmask=0077" "dmask=0077" ];
	};

	swapDevices = [
		{ device = "/dev/disk/by-uuid/e6660b98-03f2-40fb-8433-50e0017d9d15"; }
	];

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware = {
		cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
	};
}
